### ISSUE TITLE
Add link to website subscribe page

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#202]
As a new app user,
I want to subscribe to Stockpile
so that I can use the app.

Depends on [stockpileapp.co/#13](https://github.com/stockpile-co/stockpileapp.co/issues/13).

**Comment by emmanuelroussel** [comment]
Since it is our goal to make this into a paying service, tt actually would be more appropriate to simply have a link to our website where the user can subscribe and create their account.
