### ISSUE TITLE
Publish app to the App Store

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#242]

**Comment by AdamVig** [comment]
Depends on [stockpileapp.co/#3](https://github.com/stockpile-co/stockpileapp.co/issues/3) because the app store listings require a working privacy policy URL.

**Comment by emroussel** [comment]
Could you simply host the privacy policy as plain html at `https://stockpileapp.co/privacy-policy` for now?

**Comment by AdamVig** [comment]
Already did!

**Comment by emroussel** [comment]
Great! Is the app published then?

**Comment by AdamVig** [comment]
Not yet. Published on the Play store [here](https://play.google.com/store/apps/details?id=co.stockpileapp.stockpile), though.
