### ISSUE TITLE
Fix kit creation

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#250]
When creating a kit, setting the name wipes out any added items. Steps to reproduce:
- create a kit
- add one or more items to the kit
- set the name of the kit
- weird loading sequence, then all items previously added to the kit are removed and you have to start over

I was unable to reproduce on browser or mobile.

**Comment by AdamVig** [comment]
Needs testing after #297 is complete.

**Comment by emroussel** [comment]
Cannot reproduce, so #297 must have fixed it
