### ISSUE TITLE
Implement ngrx

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#297]
There are several issues with having each page's data isolated from each other, but here are the two main concerns:

First, whenever something changes (kit or item is created, edited or deleted), other pages have to update their data. This is currently done by publishing events and having the other pages listen to those events and update their local data accordingly. However, this creates a lot of extra code and is prompt to errors and bugs if we forget to take care of an event. Another solution would be to have every page reload the data from the api whenever the user enters them, but this would create a lot more api requests than necessary and would slow the app down (because of the wait for responses from the api).

Second, this architecture makes caching very difficult. For the same reasons as mentioned before, it is hard to store data locally and make sure that the data is consistent throughout the app.

Having a central store would hopefully solve both of these.

[ngrx/store](https://github.com/ngrx/store) seems like a good place to start.

**Comment by AdamVig** [comment]
Depends on [api/#251](https://github.com/stockpile-co/api/issues/251).
