### ISSUE TITLE
Remove ability to type barcode on mobile

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#298]
This is very useful for testing in browser during development, but is becoming less important on mobile. It might actually even make more sense to remove the ability to type barcodes to ensure that people have the items with them instead of simply entering barcodes.

This also makes less sense to have now that barcodes might not come with labels that are easy to type and can bring some confusion when offering the user two options to add items instead of one.

Our clients also have mentioned that this is not a feature they are likely to use.

@AdamVig what do you think?

**Comment by AdamVig** [comment]
Strongly agree. All of your points, and it simplifies the UX (removes confusing almost-redundant buttons).
