### ISSUE TITLE
Use tabs instead of side menu

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#316]
Moving the options from the side menu to tabs might make sense. Tabs are easier to access and find. We also don't have many features available so far, so they would all fit the tab bar.

However, it might cause a problem when adding custom fields, organization management and field (brand, model, category) management, since there can't be a tab for each one of those.

An option might be to decide/find out through use testing which features are used the most, put those in the tab bar and put the rest in the side menu. If we do this, there probably shouldn't be more than 4 or 5 tabs.

@AdamVig what do you think?

**Comment by AdamVig** [comment]
@emroussel When you say tabs, do you mean top tabs or bottom tabs?

I like the idea of well-defined purposes for the side menu and tabs. Can you write up a list of app functions, separated into either side menu or tabs, depending on where you think they belong? That would be helpful for me to look at so I can provide better feedback.

**Comment by emroussel** [comment]
Bottom tabs on iOS, top on Android.

I think tabs could be Scan, Inventory, Kits, Account.

In the side menu, custom fields, brand/model/category management (panel to create, update or delete) and organization management.

This is just what I think though, we should ask our clients and back this with data about what users use the most often.

**Comment by AdamVig** [comment]
I agree with all of that, except I think that Account belongs in the side menu, because I doubt it is a feature that users will use every day.

If you agree, then let's use the modified list above as our starting point, and gather feedback about actual usage once our clients are actually using the app daily.

**Comment by emroussel** [comment]
Ok the only change would be to move kits to the tab bar then.
