### ISSUE TITLE
Add nav guards

### ISSUE THREAD

**Issue by emroussel** [stockpile-co/app#66]
Look into [Ionic's nav guards](https://ionicframework.com/docs/v2/api/navigation/NavController/#nav-guards) and [angular2-jwt's auth guards](https://github.com/auth0/angular2-jwt#checking-authentication-to-hideshow-elements-and-handle-routing) and if it would be worth it to implement this function into the app.

**Comment by AdamVig** [comment]
Closed as irrelevant for now.
